### ISSUE TITLE
Erro with dash 2.3.0

### ISSUE THREAD

**Issue by remseven** [wjm41/molplotly#14]
Hello,

First of all thanks for this great package.

Today, I got the following error while importing molplotly whereas I previously had no issue:
ImportError: cannot import name 'Input' from 'dash'

As my version of dash was a bit old 1.6 I believe, I upgraded it to version 2.3.0 via pip. The import error disappeared but I had another error when trying to run the server "app.run_server(mode='inline', port=8003, height=800)":
AttributeError: ('Read-only: can only be set in the Dash constructor or during init_app()', 'requests_pathname_prefix')

I have managed to get around by downgrading dash to version 2.0.0 as recommended here [https://stackoverflow.com/questions/70908709/jupyterdash-app-run-server-error-using-jupyter-notebook](url), but there may be something to look into...

Thanks again

**Comment by wjm41** [comment]
Thanks for flagging the issue! I will update the package and make sure dash is kept at v2.0.0 :)

**Comment by wjm41** [comment]
I've updated the dependencies in v1.1.2 should it should work now - could you try updating the package with `pip install --upgrade molplotly`?

**Comment by remseven** [comment]
Apologies for the delay, but I finally got a chance to directly test a new installation of your package and it works fine. Dash was kept to v2.0.0.

**Comment by wjm41** [comment]
Great to hear!
