### ISSUE TITLE
Plotting in a running Dash app

### ISSUE THREAD

**Issue by ArnaudGaudry** [wjm41/molplotly#15]
Hi!
I have a small dash app that I use to explore the molecules present in different samples. It is possible to select the samples of interest and then display a plotly scatter plot generated using the structures. I tried to add the molplotly layer on the scatter plot but no molecules are displayed. Any experience on that?
Thanks!

**Comment by wjm41** [comment]
Hi @ArnaudGaudry! Could you give some details/example code on the issue? If my understanding is correct, the scatterplot is created within another Dash app? If so then perhaps you could copy/paste the `display_hover` function from the molplotly source code into your dash app for a custom display of the molecule images on mouseover.

**Comment by ArnaudGaudry** [comment]
Thanks for the prompt answer @wjm41 ! I could adapt the ```display_over``` function in new callback and it now works like a charm!
