### ISSUE TITLE
Removed support for python 3.7

### ISSUE THREAD

**Issue by jannisborn** [wjm41/molplotly#16]
Thanks for the great library, really useful!

You pinned the pandas version to `~=1.4.1` which effectively cuts of users that use python<3.7. See the pandas release notes:
https://pandas.pydata.org/docs/whatsnew/v1.4.0.html

Is this intentional? Which novel features from pandas >1.4.0 are strictly necessary to keep the package running?
I'll create a PR with a relaxed pandas requirements that works fine for me in a python3.7 env.

**Comment by wjm41** [comment]
This wasn't intentional, I was only setting strict requirements to prevent anymore unexpected breaking of the package - will merge your PR now, thanks!
