### ISSUE TITLE
Dependency versions for pip install

### ISSUE THREAD

**Issue by kjelljorner** [wjm41/molplotly#18]
Is there some reason for the very specific version requirements for the dependencies? For the pip install I would loosen this up unless there are any particular known issues.

**Comment by wjm41** [comment]
Sorry for the late response! I got burnt by dash making an update just a day before releasing molplotly and breaking the package so I tightened the dependencies a lot, but that was an overreaction on my part and I can see it being annoying for environment management - I'll loosen it up shortly!

**Comment by wjm41** [comment]
I've loosened the dependencies now - upgrade to v1.1.4 and let me know if you have any other issues :)

**Comment by kjelljorner** [comment]
Thanks! I tried an install now from PyPI and it worked perfectly.
