### ISSUE TITLE
Integrating scatterplot with 3D molecule structures in existing Dash app

### ISSUE THREAD

**Issue by mwannier30** [wjm41/molplotly#22]
Thanks for the great package!

I am interested in integrating a scatterplot with the 3D structures of my molecules in an existing Dash app. What would be the best way to do this (if it's even possible), considering that the add_molecules() function already returns a Dash app?

Thanks for your help! :)

Edit: My bad, didn't saw issue #15 !

**Comment by wjm41** [comment]
Ah sorry I didn't see this until now! Hope that answer is helpful - let me know if there's anything I could clarify about the function :)
