### ISSUE TITLE
"Invalid prop" and "Callback error"

### ISSUE THREAD

**Issue by hfswetton** [wjm41/molplotly#23]
Hi,

This may be an error specific to my device (running MacOS Monterey 12.6.3), but Dash currently seems to raise an error when trying to use this package. As a minimal working example, I created a fresh environment using Mambaforge (tested both with Python 3.8 and Python 3.11) and copied the install commands & sample notebook from the package's Readme. When running the notebook as-is, the tooltips would simply not pop up, but after removing `mode='inline'` and  viewing the graph through my browser, the browser showed me a "Callback error" each time I hovered over a datapoint (see attached screenshot). Additionally, it provided the error "Invalid prop for this component" upon loading.

The error seems to be fixed (at least in python 3.11) by replacing `df_row[title_col].astype(str)` in line 333 of `molplotly.main` with `str(df_row[title_col])` (for some reason, `.astype(str)` seems to work with numeric `dtype`s but not with strings as the item returned by `df_row[title_col]` is the string itself). After making this change, the single "Invalid prop..." error remains, but the tooltip seems to work as intended without throwing the "Callback error"s.

The exact error messages were as follows:
```
Invalid prop for this component
-------------------------------
Property "value" was used with component ID:
  "smiles-menu"
in one of the Input items of a callback.
This ID is assigned to a dash_core_components.Store component
in the layout, which does not support this property.
This ID was used in the callback(s) for Output(s):
  graph-tooltip.show, graph-tooltip.bbox, graph-tooltip.children
```

```
Callback error updating ..graph-tooltip.show...graph-tooltip.bbox...graph-tooltip.children..
--------------------------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
AttributeError: 'str' object has no attribute 'astype'
```

<img width="2541" alt="Screenshot 2023-03-10 at 14 23 46" src="https://user-images.githubusercontent.com/15179848/224327371-366cd8b5-512b-4dd1-9048-a9a5e509a972.png">

**Comment by wjm41** [comment]
Thanks for raising the issue! I think you have found an important bug that breaks molplotly because of some updates to pandas/jupyter-dash - I think I have found a fix to the "invalid prop" error, and will release a new version of molplotly once I have checked that it works :)

**Comment by wjm41** [comment]
I've updated molplotly to v1.1.6 which should fix this problem - could you try updating to v1.1.6 (`pip install molplotly==1.1.6`) and seeing if this still crops up for you?

**Comment by hfswetton** [comment]
That's great, thanks for the update and sorry for the late reply! I think the fix you found is the same workaround I ended up using, which fixed the issue for me too. I just checked again with version 1.1.7 (within a notebook) and seems to work perfectly now.
