### ISSUE TITLE
make image background transparent 

### ISSUE THREAD

**Issue by JBostrom** [wjm41/molplotly#3]
It would be great to make the image background transparent allowing what’s behind it to show through.

**Comment by wjm41** [comment]
Thanks for the suggestion! I managed to get SVG images showing and give the hover box variable opacity so it looks something like this:

<img width="453" alt="Screenshot 2022-02-15 at 21 29 26" src="https://user-images.githubusercontent.com/17111438/154153325-d179556c-1174-4530-98b2-47db530ef7d3.png">

I will merge this feature along with a couple of other ones later on this week :)

**Comment by JBostrom** [comment]
Cool, looks great William. Thanks!

**Comment by wjm41** [comment]
The feature has been added in merge #7 :) I will make a new release shortly once I've updated the docs
