### ISSUE TITLE
Pip install error

### ISSUE THREAD

**Issue by ArnaudGaudry** [wjm41/molplotly#5]
Great idea this package!
I however ran into an issue during installation:
`UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 1822: character maps to <undefined>`
This is certainly due to unusal characters in the readme, since I could install the package locally by editing the readme file. 
Cheers!

**Comment by jannisborn** [comment]
Why not submitting a PR directly then? :)

**Comment by wjm41** [comment]
@ArnaudGaudry sorry for the late reply! Could you post what edit you made to the readme file? Thanks :)

**Comment by ArnaudGaudry** [comment]
Hi! I edited the readme in a rather brutal way, that's why I didn't make a pull request ;). Here is the edited version which allows local installation. Cheers!
[README.md](https://github.com/wjm41/molplotly/files/8163355/README.md)

**Comment by wjm41** [comment]
Ah I see! Let me remove the emojis from the README, hopefully that'll fix the issues you have!
